version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    environment:
      - GO_ENV=development
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
volumes:
  pgdata:
networks:
  app-network:
    driver: bridge
